In [1]:
import torch
import numpy as np

# Operaciones con tensores

*Las operaciones más comunes son:*
1. *Suma.*
2. *Resta.*
3. *Multiplicación.*
4. *División.*
5. *Producto de matrices.*

In [2]:
X = torch.tensor([1, 2, 3], device='mps')
X

tensor([1, 2, 3], device='mps:0')

*Podemos ver que las primeras cuatro operaciones (i.e., suma, resta, multiplicación y división) se realizan elemento a elemento, al igual que en NumPy. Por ejemplo, si la operación es $X + 100$, al primer elemento del tensor $X$ le sumamos 100, al segundo elemento del tensor $X$ se le suma 100, y así para todos los elementos.*

In [3]:
# Suma
print(f'X: {X}')
y = X + 100
print(f'y: {y}')

X: tensor([1, 2, 3], device='mps:0')
y: tensor([101, 102, 103], device='mps:0')


In [8]:
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')
y = torch.randint_like(X, low=0, high=10)
print(f'y:\n {y}')

z = X + y
print(f'Suma:\n {z}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
y:
 tensor([[7., 2., 2.],
        [7., 3., 3.],
        [3., 7., 8.]], device='mps:0')
Suma:
 tensor([[8., 3., 3.],
        [8., 4., 4.],
        [4., 8., 9.]], device='mps:0')


In [4]:
# Resta
print(f'X: {X}')
y = X - 100
print(f'y: {y}')

X: tensor([1, 2, 3], device='mps:0')
y: tensor([-99, -98, -97], device='mps:0')


In [5]:
# Multiplicación
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')

y = X * 25
print(f'Multiply X by 25:\n {y}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
Multiply X by 25:
 tensor([[25., 25., 25.],
        [25., 25., 25.],
        [25., 25., 25.]], device='mps:0')


In [7]:
# División
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')

y = X / 25
print(f'Divide X by 25:\n {y}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
Divide X by 25:
 tensor([[0.0400, 0.0400, 0.0400],
        [0.0400, 0.0400, 0.0400],
        [0.0400, 0.0400, 0.0400]], device='mps:0')
