In [1]:
import torch

# Operaciones con tensores

*Las operaciones más comunes son:*
1. *Suma.*
2. *Resta.*
3. *Multiplicación.*
4. *División.*
5. *Producto de matrices.*

In [2]:
X = torch.tensor([1, 2, 3], device='mps')
X

tensor([1, 2, 3], device='mps:0')

*Podemos ver que las primeras cuatro operaciones (i.e., suma, resta, multiplicación y división) se realizan elemento a elemento, al igual que en NumPy. Por ejemplo, si la operación es $X + 100$, al primer elemento del tensor $X$ le sumamos 100, al segundo elemento del tensor $X$ se le suma 100, y así para todos los elementos.*

In [3]:
# Suma
print(f'X: {X}')
y = X + 100
print(f'y: {y}')

X: tensor([1, 2, 3], device='mps:0')
y: tensor([101, 102, 103], device='mps:0')


In [4]:
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')
y = torch.randint_like(X, low=0, high=10)
print(f'y:\n {y}')

z = X + y
print(f'Suma:\n {z}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
y:
 tensor([[2., 4., 8.],
        [8., 0., 1.],
        [3., 7., 2.]], device='mps:0')
Suma:
 tensor([[3., 5., 9.],
        [9., 1., 2.],
        [4., 8., 3.]], device='mps:0')


In [5]:
# Resta
print(f'X: {X}')
y = X - 100
print(f'y: {y}')

X: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
y: tensor([[-99., -99., -99.],
        [-99., -99., -99.],
        [-99., -99., -99.]], device='mps:0')


In [6]:
# Multiplicación
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')

y = X * 25
print(f'Multiply X by 25:\n {y}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
Multiply X by 25:
 tensor([[25., 25., 25.],
        [25., 25., 25.],
        [25., 25., 25.]], device='mps:0')


In [7]:
# División
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')

y = X / 25
print(f'Divide X by 25:\n {y}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
Divide X by 25:
 tensor([[0.0400, 0.0400, 0.0400],
        [0.0400, 0.0400, 0.0400],
        [0.0400, 0.0400, 0.0400]], device='mps:0')


## Multipliación de matrices

*En PyTorch tenemos dos formas de multiplicar matrices:*
1. ***Multiplicación elemento a elemento (element-wise product).** Matemáticamente, no es una operación valida entre matrices, pero PyTorch nos permite realizar esa multiplicación donde el elemento $a_{i,j}$ de la matriz $A$ se multiplica con el elemento $b_{i,j}$ de la matriz $B$.*
    - *Para poder realizar la multiplicación elemento a elemento, las matrices deben tener las mismas dimensiones.*
2. ***Producto de matrices (dot product).** Esta es la multiplicación matemáticamente correcta de matrices.*
    - *Las dimensiones de las matrices deben ser compatibles. Es decir, la cantidad de columnas en la matriz $A$ tiene que ser equivalente a la cantidad de filas de en la matriz $B$, por eso decimos que la multiplicación de matrices no es conmutativa (i.e., $A\cdot B$ no es lo mismo que $B\cdot A$).*
    - *Si $A$ es una matriz de tamaño $m \times n$ y $B$ es una matriz de tamaño $n \times p$, entonces el producto de matrices $A \cdot B$ es una matriz de tamaño $m \times p$.*

### Multiplicación elemento a elemento

In [8]:
A = torch.randint(low=0, high=10, size=(3, 3), device='mps')
B = torch.randint(low=0, high=10, size=(3, 3), device='mps')
print(f'A:\n {A}')
print(f'B:\n {B}')

A:
 tensor([[4, 9, 8],
        [8, 8, 6],
        [2, 9, 5]], device='mps:0')
B:
 tensor([[6, 7, 9],
        [9, 1, 5],
        [0, 0, 5]], device='mps:0')


In [9]:
C = A * B
print(f'A * B =\n {C}')

A * B =
 tensor([[24, 63, 72],
        [72,  8, 30],
        [ 0,  0, 25]], device='mps:0')


### Producto de matrices

*Para el producto de matrices podemos utilizar las funciones `torch.matmul` y `torch.mm`, o el operador `@`.*

In [10]:
# Change device type to CPU because MPS does not support matrix multiplication for integers
A = torch.randint(low=0, high=10, size=(3, 2), device='cpu')
B = torch.randint(low=0, high=10, size=(2, 3), device='cpu')

# Matrix multiplication
C = torch.mm(A, B)
print(f'A @ B =\n {C}')

A @ B =
 tensor([[75, 16, 93],
        [12,  2, 16],
        [ 9,  3,  9]])


In [11]:
# Matrix multiplication using the @ operator
print(A @ B)

tensor([[75, 16, 93],
        [12,  2, 16],
        [ 9,  3,  9]])


*Podemos transponer fácilmente una matriz utilizando la función `torch.transpose` o el método `.T`. Esto suele ser muy útil al tener que multiplicar matrices.*

In [12]:
# Create two random tensors with the same shape
tensor_A = torch.rand(size=(3, 2))
tensor_B = torch.rand(size=(3, 2))

print(f'Original shapes: tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.shape}')

# Transpose the tensors
tensor_C = torch.mm(tensor_A, tensor_B.T)
print(f'Shapes after transpose: tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.T.shape}')

# Output:
print(f'Output:\n {tensor_C}')

Original shapes: tensor_A = torch.Size([3, 2]) and tensor_B = torch.Size([3, 2])
Shapes after transpose: tensor_A = torch.Size([3, 2]) and tensor_B = torch.Size([2, 3])
Output:
 tensor([[0.7623, 0.1659, 0.5608],
        [0.9334, 0.1653, 0.3865],
        [0.7834, 0.1416, 0.3469]])


# Agregación de tensores

*Estas operaciones nos permiten obtener un único valor a partir de un tensor. Por ejemplo, la suma de los elementos del tensor, el valor máximo, el valor mínimo, el valor promedio, entre otros.*

In [13]:
X = torch.arange(start=0, end=100, step=10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
torch.min(X), X.min()

(tensor(0), tensor(0))

In [15]:
torch.max(X), X.max()

(tensor(90), tensor(90))

In [16]:
# We must change the datatype to float32 because torch.mean() does not support int64
torch.mean(X.type(torch.float32)), X.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [17]:
torch.sum(X), X.sum()

(tensor(450), tensor(450))

*Podemos también obtener la posición (índice) del elemento con el valor máximo/mínimo del tensor usando los métodos `argmax()` o `argmin()` respectivamente.*

In [18]:
print(f'Posición del valor máximo: {X.argmax()}')
print(f'Posición del valor mínimo: {X.argmin()}')

Posición del valor máximo: 9
Posición del valor mínimo: 0
