In [1]:
import torch

# Indexing

*Creamos, a partir de las matrices `A` y `B`, un tensor de dimensión $2\times 3\times 3$.*

In [13]:
A = torch.arange(1, 10).reshape((3, 3))
print(f'Matriz A:\n{A}')

B = torch.arange(10, 19).reshape((3, 3))
print(f'Matriz B:\n{B}')

Matriz A:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Matriz B:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [14]:
X = torch.stack((A, B))
print(f'Tensor X:\n{X}')
print(f'Shape: X = {X.shape}')

Tensor X:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Shape: X = torch.Size([2, 3, 3])


*Podemos acceder a los elementos de cada dimensión utilizando `[]`. Por ejemplo, para acceder a los elementos de nuestro tensor `X` podemos utilizar:*
- *`X[0]` nos devuelve el primer elemento de la primera dimensión. En nuestro ejemplo, nos devuelve la matriz `A`. Si quisiéramos acceder a la matriz `B`, deberíamos usar `X[1]`. Si tuviésemos más elementos en la primera dimensión, para acceder a ellos deberíamos incrementar gradualmente el índice.*
- *`X[0, 0]` nos devuelve el primer elemento de la primera dimensión y el primer elemento de la segunda dimensión. En nuestro ejemplo, nos devuelve la primera fila de la matriz `A`.*
- *`X[0, 0, 0]` nos devuelve el primer elemento de las tres dimensiones. Es decir, nos devuelve el primer elemento en la primera fila de la matriz `A`.*

In [15]:
print(f'X = {X[0]}\n')
print(f'Shape: X = {X[0].shape}')

Tensor: X = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Shape: X = torch.Size([3, 3])


In [16]:
print(f'Matrix: A = {X[0]}\n')
print(f'Shape: A = {X[0].shape}')

Matrix: A = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Shape: A = torch.Size([3, 3])


In [18]:
print(f'First row in matrix A = {X[0, 0]}')

First row in matrix A = tensor([1, 2, 3])


In [19]:
print(f'First element of matrix A = {X[0, 0, 0]}')

First element of matrix A = 1


*Si quisiéramos acceder a un elemento no existente en el tensor, obtendríamos un error. Por ejemplo, si quisiéramos acceder a `X[2]`, obtendríamos un error porque no existe un tercer elemento en la primera dimensión.*

In [21]:
try:
    print(f'X[2] = {X[2]}')
except IndexError as e:
    print(f'Error: {e}')

Error: index 2 is out of bounds for dimension 0 with size 2
