In [1]:
import torch

# Tensor operations

*The most common operations are:*
1. *Addition.*
2. *Subtraction.*
3. *Multiplication.*
4. *Division.*
5. *Matrix multiplication.*

In [2]:
X = torch.tensor([1, 2, 3], device='mps')
X

tensor([1, 2, 3], device='mps:0')

- *We can see that the first four operations (i.e., addition, subtraction, multiplication, and division) are performed element-wise, just like in NumPy. For example, if the operation is $X + 100$, we add 100 to the first element of tensor $X$, 100 is added to the second element of tensor $X$, and so on for all elements.*

In [3]:
# Suma
print(f'X: {X}')
y = X + 100
print(f'y: {y}')

X: tensor([1, 2, 3], device='mps:0')
y: tensor([101, 102, 103], device='mps:0')


In [4]:
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')
y = torch.randint_like(X, low=0, high=10)
print(f'y:\n {y}')

z = X + y
print(f'Suma:\n {z}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
y:
 tensor([[2., 4., 8.],
        [8., 0., 1.],
        [3., 7., 2.]], device='mps:0')
Suma:
 tensor([[3., 5., 9.],
        [9., 1., 2.],
        [4., 8., 3.]], device='mps:0')


In [5]:
# Resta
print(f'X: {X}')
y = X - 100
print(f'y: {y}')

X: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
y: tensor([[-99., -99., -99.],
        [-99., -99., -99.],
        [-99., -99., -99.]], device='mps:0')


In [6]:
# Multiplicación
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')

y = X * 25
print(f'Multiply X by 25:\n {y}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
Multiply X by 25:
 tensor([[25., 25., 25.],
        [25., 25., 25.],
        [25., 25., 25.]], device='mps:0')


In [7]:
# División
X = torch.ones(size=(3, 3), device='mps')
print(f'X:\n {X}')

y = X / 25
print(f'Divide X by 25:\n {y}')

X:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
Divide X by 25:
 tensor([[0.0400, 0.0400, 0.0400],
        [0.0400, 0.0400, 0.0400],
        [0.0400, 0.0400, 0.0400]], device='mps:0')


## Matrix multiplication

- *In PyTorch we have two ways to multiply matrices:*
    1. ***Element-wise multiplication (element-wise product).** Mathematically, this is not a valid operation between matrices, but PyTorch allows us to perform this multiplication where element $a_{i,j}$ of matrix $A$ is multiplied by element $b_{i,j}$ of matrix $B$.*
        - *To perform element-wise multiplication, the matrices must have the same dimensions.*
    2. ***Matrix multiplication (dot product).** This is the mathematically correct multiplication of matrices.*
        - *The dimensions of the matrices must be compatible. That is, the number of columns in matrix $A$ must be equivalent to the number of rows in matrix $B$, which is why we say that matrix multiplication is not commutative (i.e., $A\cdot B$ is not the same as $B\cdot A$).*
        - *If $A$ is a matrix of size $m \times n$ and $B$ is a matrix of size $n \times p$, then the matrix product $A \cdot B$ is a matrix of size $m \times p$.*

### Element-wise multiplication

In [8]:
A = torch.randint(low=0, high=10, size=(3, 3), device='mps')
B = torch.randint(low=0, high=10, size=(3, 3), device='mps')
print(f'A:\n {A}')
print(f'B:\n {B}')

A:
 tensor([[4, 9, 8],
        [8, 8, 6],
        [2, 9, 5]], device='mps:0')
B:
 tensor([[6, 7, 9],
        [9, 1, 5],
        [0, 0, 5]], device='mps:0')


In [9]:
C = A * B
print(f'A * B =\n {C}')

A * B =
 tensor([[24, 63, 72],
        [72,  8, 30],
        [ 0,  0, 25]], device='mps:0')


### Matrix product

- *For matrix multiplication we can use the `torch.matmul` and `torch.mm` functions, or the `@` operator.*

In [10]:
# Change device type to CPU because MPS does not support matrix multiplication for integers
A = torch.randint(low=0, high=10, size=(3, 2), device='cpu')
B = torch.randint(low=0, high=10, size=(2, 3), device='cpu')

# Matrix multiplication
C = torch.mm(A, B)
print(f'A @ B =\n {C}')

A @ B =
 tensor([[75, 16, 93],
        [12,  2, 16],
        [ 9,  3,  9]])


In [11]:
# Matrix multiplication using the @ operator
print(A @ B)

tensor([[75, 16, 93],
        [12,  2, 16],
        [ 9,  3,  9]])


- *We can easily transpose a matrix using the `torch.transpose` function or the `.T` method. This is often very useful when having to multiply matrices.*

In [12]:
# Create two random tensors with the same shape
tensor_A = torch.rand(size=(3, 2))
tensor_B = torch.rand(size=(3, 2))

print(f'Original shapes: tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.shape}')

# Transpose the tensors
tensor_C = torch.mm(tensor_A, tensor_B.T)
print(f'Shapes after transpose: tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.T.shape}')

# Output:
print(f'Output:\n {tensor_C}')

Original shapes: tensor_A = torch.Size([3, 2]) and tensor_B = torch.Size([3, 2])
Shapes after transpose: tensor_A = torch.Size([3, 2]) and tensor_B = torch.Size([2, 3])
Output:
 tensor([[0.7623, 0.1659, 0.5608],
        [0.9334, 0.1653, 0.3865],
        [0.7834, 0.1416, 0.3469]])


# Tensor aggregation

- *These operations allow us to obtain a single value from a tensor. For example, the sum of the tensor elements, the maximum value, the minimum value, the average value, among others.*

In [13]:
X = torch.arange(start=0, end=100, step=10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
torch.min(X), X.min()

(tensor(0), tensor(0))

In [15]:
torch.max(X), X.max()

(tensor(90), tensor(90))

In [16]:
# We must change the datatype to float32 because torch.mean() does not support int64
torch.mean(X.type(torch.float32)), X.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [17]:
torch.sum(X), X.sum()

(tensor(450), tensor(450))

- *We can also get the position (index) of the element with the maximum/minimum value of the tensor using the `argmax()` or `argmin()` methods, respectively.*

In [18]:
print(f'Posición del valor máximo: {X.argmax()}')
print(f'Posición del valor mínimo: {X.argmin()}')

Posición del valor máximo: 9
Posición del valor mínimo: 0
