In [23]:
import torch

# Indexing

- *Starting with matrices `A` and `B`, we build a tensor with shape $2 \times 3 \times 3$. This means our tensor stacks both matrices along a new dimension, giving us a 3D structure that's easy to index and manipulate.*

In [24]:
A = torch.arange(1, 10).reshape((3, 3))
print(f'Matriz A:\n{A}')

B = torch.arange(10, 19).reshape((3, 3))
print(f'Matriz B:\n{B}')

Matriz A:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Matriz B:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [25]:
X = torch.stack((A, B))
print(f'Tensor X:\n{X}')
print(f'Shape: X = {X.shape}')

Tensor X:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Shape: X = torch.Size([2, 3, 3])


- *You can access elements in each dimension of a tensor using square brackets `[]`. For example, with our tensor `X`:*
    - *`X[0]` grabs the first item along the first dimension—so in our case, that's matrix `A`. To get matrix `B`, use `X[1]`.*
    - *`X[0, 0]` dives deeper: it fetches the first row of matrix `A` (the first element of the first and second dimensions).*
    - *`X[0, 0, 0]` goes all the way—this returns the very first element in the first row of matrix `A` (the first element in all three dimensions).*

In [26]:
print(f'X = {X[0]}\n')
print(f'Shape: X = {X[0].shape}')

X = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Shape: X = torch.Size([3, 3])


In [27]:
print(f'Matrix: A = {X[0]}\n')
print(f'Shape: A = {X[0].shape}')

Matrix: A = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Shape: A = torch.Size([3, 3])


In [28]:
print(f'First row in matrix A = {X[0, 0]}')

First row in matrix A = tensor([1, 2, 3])


In [29]:
print(f'First element of matrix A = {X[0, 0, 0]}')

First element of matrix A = 1


- *Trying to access an element that doesn't exist in our tensor will throw an error. For instance, if you try `X[2]`, you'll get an error—there's no third matrix stacked in the first dimension, so PyTorch lets you know you're out of bounds.*

In [30]:
try:
    print(f'X[2] = {X[2]}')
except IndexError as e:
    print(f'Error: {e}')

Error: index 2 is out of bounds for dimension 0 with size 2


- *Slicing lets us grab just the parts of a tensor we want. For example, `X[1, 1:, 1:]` pulls out the last two rows and last two columns from matrix `B`. It's a handy way to focus on specific sections without copying or reshaping the whole tensor.*

In [32]:
X[1, 1:, 1:]

tensor([[14, 15],
        [17, 18]])